# Generated by Django 4.1.4 on 2024-10-15 02:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entregador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
                ('telefone', models.CharField(blank=True, max_length=14, null=True)),
                ('vaiculo', models.CharField(blank=True, max_length=50, null=True)),
                ('placa', models.CharField(blank=True, max_length=7, null=True)),
                ('cadastro', models.DateField(default=datetime.datetime(2024, 10, 14, 23, 46, 1, 450289))),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Adm - Entregador',
                'verbose_name_plural': 'Adm - Entregador',
            },
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name': '3 - Pedido', 'verbose_name_plural': '3 - Pedido'},
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='entrega',
            new_name='entregue',
        ),
        migrations.AddField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(default=0, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_pedido',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 14, 23, 46, 1, 450289)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pagamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='myapp.formapagamento'),
        ),
        migrations.CreateModel(
            name='ItensCarrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto', to='myapp.produto')),
            ],
            options={
                'verbose_name': '3 - Itens do Carrinho',
                'verbose_name_plural': '3 - Itens do Carrinho',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='entregador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='myapp.entregador'),
        ),
    ]
