# Generated by Django 4.1.4 on 2024-10-15 02:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_entregador_alter_pedido_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobertura',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='embalagem',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='entregador',
            name='cadastro',
            field=models.DateField(default=datetime.datetime(2024, 10, 14, 23, 53, 59, 253378)),
        ),
        migrations.AlterField(
            model_name='formapagamento',
            name='nome',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_pedido',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 14, 23, 53, 59, 253378)),
        ),
        migrations.AlterField(
            model_name='tipomercadoria',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='unidademedida',
            name='um',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='base',
            unique_together={('tipo', 'um', 'embalagem')},
        ),
        migrations.AlterUniqueTogether(
            name='produto',
            unique_together={('base', 'sabor', 'preco')},
        ),
    ]
