# Generated by Django 4.1.4 on 2024-10-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_cobertura_montapote_sabor_tiposabor_selsabor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selsabor',
            name='quantidade_bolas',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
