# Generated by Django 4.1.4 on 2024-10-09 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_selsabor_quantidade_bolas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='montapote',
            options={'verbose_name': 'A - MontaPote', 'verbose_name_plural': 'A - MontaPote'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedido'},
        ),
        migrations.AlterModelOptions(
            name='sacolaitens',
            options={'verbose_name': 'B - Itens da Sacola', 'verbose_name_plural': 'B - Itens da Sacola'},
        ),
        migrations.AlterModelOptions(
            name='selsabor',
            options={'verbose_name': 'Selecinar Sabor', 'verbose_name_plural': 'Selecinar Sabor'},
        ),
    ]
