# Generated by Django 4.1.4 on 2024-10-15 20:45

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_cobertura_nome_alter_embalagem_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregador',
            name='cadastro',
            field=models.DateField(default=datetime.datetime(2024, 10, 15, 17, 45, 14, 379891)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_pedido',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
