# Generated by Django 4.1.4 on 2024-10-15 22:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_entregador_cadastro_alter_pedido_data_pedido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itenscarrinho',
            options={},
        ),
        migrations.AlterField(
            model_name='entregador',
            name='cadastro',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
