# Generated by Django 4.1.4 on 2024-10-12 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_sacolaitens_options_alter_pedido_pago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='montapote',
            name='coberturas',
        ),
    ]
