# Generated by Django 4.1.4 on 2024-10-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_montapote_coberturas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sacolaitens',
            options={'verbose_name': 'B - Itens da Sacola', 'verbose_name_plural': 'B - Itens da Sacola'},
        ),
        migrations.AlterModelOptions(
            name='selcobertura',
            options={},
        ),
        migrations.AddField(
            model_name='pedido',
            name='endereco',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='entrega',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pagamento',
            field=models.CharField(choices=[('CARTAO', 'Cartão'), ('PIX', 'Pix'), ('DINHEIRO', 'Dinheiro'), ('BOLETO', 'Boleto'), ('CHEQUE', 'Cheque')], max_length=100, null=True),
        ),
    ]
