# Generated by Django 4.1.4 on 2024-10-13 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_sacolaitens_options_alter_selcobertura_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Embalagem',
            new_name='Produto',
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name': '1 - Produto', 'verbose_name_plural': '1 - Produto'},
        ),
        migrations.RemoveField(
            model_name='montapote',
            name='embalagem',
        ),
        migrations.AddField(
            model_name='montapote',
            name='Produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Produto', to='myapp.produto'),
        ),
    ]
