# Generated by Django 4.1.4 on 2024-10-13 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_embalagem_produto_alter_produto_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('capacidade_maxima_bolas', models.PositiveIntegerField(default=1)),
                ('ativo', models.BooleanField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': '1 - Base',
                'verbose_name_plural': '1 - Base',
            },
        ),
        migrations.RemoveField(
            model_name='montapote',
            name='Produto',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.AddField(
            model_name='montapote',
            name='base',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base', to='myapp.base'),
        ),
    ]
